daily_affirmations = [
    "Loving myself is essential to my happiness",
    "I deserve to go after my goals and do what makes me happy",
    "I find it easy to recognize my positive qualities",
    "Being happy with myself is a normal part of my everyday life",
    "I find it easy to be confident and comfortable with who I am",
    "Accepting myself unconditionally gives me the power to succeed",
    "I know I have the right to be happy and nothing can take that away from me",
    "I truly like myself and this helps others to accept me for who I am",
    "I have a natural awareness of all the positive things in my life",
    "I am a unique person and I love myself for who I am",
    "I am turning into someone who is naturally motivated",
    "Every day I become more driven, motivated and ambitious",
    "I will become a naturally motivated, highly ambitious person",
    "I will be hugely motivated and productive",
    "Today, and every day, I choose to be confident",
    "I radiate confidence, certainty and optimism",
    "I courageously open and move through every door of opportunity",
    "I have the power to live my dreams",
    "My mind has unlimited power",
    "I stand up for what I believe in",
    "I act with courage and confidence",
    "I believe in myself",
    "What I did is in the past and now I can create my future",
    "I forgive everyone that has hurt me in the past and move forward with a cleansed soul",
    "I am rich in health, wealth and love",
    "Opportunities and advantages come with each door that I open",
    "The more I give to the world, the more I get",
    "What I currently do is serving me towards my higher purpose",
    "I have the power to change my thoughts in a second",
    "I'm allowed to do what I want with my life",
    "I have the power to change myself",
    "I allow myself to play and enjoy life",
    "I am making a difference in this world",
    "I am at peace with all that has happened, is happening, and will happen",
    "My life is just beginning",
    "Today, I abandon my old habits and take up new, more positive ones",
    "I am now free from my bad habits",
    "I only do positive habits"
]
